// The cross-runtime keyring vectors. edge-proc (Python) asserts the same file,
// so a preimage, key identity or verdict that drifts here drifts from the
// Python publisher/verifier too. The file is generated by
// scripts/generate-keyring-vectors.mjs from fixed seeds; see
// test/keyring-vectors-script.test.ts for the regeneration check.

/// <reference types="node" />

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { SignatureError } from "./crypto.js";
import {
	deriveKeyId,
	KeyRevokedError,
	type Keyring,
	parseTrustRoot,
	UnknownKeyError,
} from "./keyring.js";
import { MemoryCacheStore } from "./memoryStore.js";
import { PointerExpiredError, pointerSigningBytes, syncIndex } from "./sync.js";
import type { VersionPointer } from "./types.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const RAW = readFileSync(
	join(HERE, "__fixtures__", "keyring_vectors.json"),
	"utf8",
);

interface PointerVector {
	readonly pointer: VersionPointer;
	readonly preimage_hex: string;
	readonly signature_hex: string;
}

interface Vectors {
	readonly key_ids: Readonly<Record<string, string>>;
	readonly keyrings: Readonly<Record<string, unknown>>;
	readonly pointers: Readonly<Record<string, PointerVector>>;
	readonly outcomes: Readonly<
		Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>
	>;
}

const VECTORS = JSON.parse(RAW) as Vectors;
const ENCODER = new TextEncoder();

function hex(bytes: Uint8Array): string {
	return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(
		"",
	);
}

function fromHex(text: string): Uint8Array {
	return new Uint8Array(
		(text.match(/../gu) ?? []).map((pair) => Number.parseInt(pair, 16)),
	);
}

async function keyringNamed(name: string): Promise<Keyring> {
	return parseTrustRoot(ENCODER.encode(JSON.stringify(VECTORS.keyrings[name])));
}

class ReachedManifest extends Error {}

/** Judge one network-fetched pointer with no rollback floor. */
async function verdict(
	pointer: VersionPointer,
	keyring: Keyring,
	now: number,
): Promise<string> {
	try {
		await syncIndex({
			baseUrl: "/v",
			store: new MemoryCacheStore(),
			keyring,
			now: () => now,
			fetchBytes: (url) =>
				url.endsWith("/latest")
					? Promise.resolve(ENCODER.encode(JSON.stringify(pointer)))
					: Promise.reject(new ReachedManifest(url)),
		});
	} catch (error) {
		if (error instanceof ReachedManifest) return "ok";
		if (error instanceof PointerExpiredError) return "expired";
		if (error instanceof KeyRevokedError) return "key_revoked";
		if (error instanceof UnknownKeyError) return "unknown_key";
		if (error instanceof SignatureError) return "signature_error";
		throw error;
	}
	throw new Error("the vector manifest hash cannot resolve");
}

describe("cross-runtime keyring vectors", () => {
	it("is canonical sorted-key JSON, byte for byte", () => {
		const canonical = (value: unknown): string => {
			if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
			if (typeof value === "object" && value !== null) {
				const record = value as Record<string, unknown>;
				return `{${Object.keys(record)
					.sort()
					.map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`)
					.join(",")}}`;
			}
			return JSON.stringify(value);
		};
		expect(canonical(VECTORS)).toBe(RAW);
		expect(Object.keys(VECTORS).sort()).toEqual([
			"key_ids",
			"keyrings",
			"outcomes",
			"pointers",
		]);
	});

	it("derives each key id from its public key", async () => {
		const ring = await keyringNamed("ab");
		expect(ring.keys.map((key) => key.keyId)).toEqual([
			VECTORS.key_ids.A,
			VECTORS.key_ids.B,
		]);
		for (const key of ring.keys) {
			expect(await deriveKeyId(key.publicKey)).toBe(key.keyId);
		}
	});

	it("parses every keyring", async () => {
		for (const name of Object.keys(VECTORS.keyrings)) {
			await expect(keyringNamed(name)).resolves.toBeDefined();
		}
		expect((await keyringNamed("b_revoked_a")).revoked).toEqual([
			VECTORS.key_ids.A,
		]);
	});

	it("matches every signing preimage and signature", () => {
		for (const vector of Object.values(VECTORS.pointers)) {
			expect(hex(pointerSigningBytes(vector.pointer))).toBe(
				vector.preimage_hex,
			);
			expect(hex(fromHex(vector.signature_hex))).toBe(vector.signature_hex);
			expect(
				hex(
					Uint8Array.from(atob(vector.pointer.signature), (char) =>
						char.charCodeAt(0),
					),
				),
			).toBe(vector.signature_hex);
		}
	});

	it("verifies every pointer under the ring that trusts both keys", async () => {
		const ring = await keyringNamed("ab");
		for (const vector of Object.values(VECTORS.pointers)) {
			expect(await verdict(vector.pointer, ring, 0)).toBe("ok");
		}
	});

	it("reproduces every recorded outcome", async () => {
		let judged = 0;
		for (const [ringName, byTime] of Object.entries(VECTORS.outcomes)) {
			const ring = await keyringNamed(ringName);
			for (const [now, expected] of Object.entries(byTime)) {
				for (const [name, outcome] of Object.entries(expected)) {
					const vector = VECTORS.pointers[name];
					if (vector === undefined) throw new Error(`no pointer ${name}`);
					expect(
						await verdict(vector.pointer, ring, Number(now)),
						`${name} at ${now}`,
					).toBe(outcome);
					judged += 1;
				}
			}
		}
		expect(judged).toBe(8);
	});
});
